// Generated by https://quicktype.io

export interface Room {
    id:            number;
    roomtitle:     string;
    location:      string;
    price:         string;
    numberOfUsers: string;
    fav:           boolean;
    image:         string;
}
